# Perform continuous integration tests on pull requests
name: black

on: pull_request

jobs:
  black:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup python

        uses: actions/setup-python@v4
        with:
          python-version: 3.10.3
          cache-dependency-path: scripts/requirements_dev.txt
          cache: "pip"

      - name: Pip install
        run: pip install -r scripts/requirements_dev.txt

      - name: Black
        run: |
          echo "running black..."
          black --version
          black klippy --check

      - name: Flake8
        run: |
          echo "running flake8..."
          flake8 --config .flake8
